name = "ActiveBrownianParticles"
uuid = "72bd41b5-94e9-41b1-bed6-6f0771ba2ea7"
authors = ["SinaLewis <sile6618@colorado.edu> and contributors"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
